#!/bin/bash

# Idea for how this works and is implemented technically:
# This main script that is supposed to be called is a bash script.
# Step 1:
# , it checks whether the environment already exists, and
# if so, loads it.
# If it doesn't exist. it creates it in 
# ~/.omniax_$(uname -m)
# i.e. e.g. ~/.omniax__x86_64.
# Then it installs all modules. Then it loads the environment and the job
# continues.
# These steps are skipped, when you installed it as a module. Then,
# the module environment is the used environment.
# This logic is defined in .shellscript_functions
# Step 2:
# It checks whether sbatch is installed. If so, it will re-start
# itself as a bascript in a slurmjob.
# If not, the python-script with the parsed parameters are run directly.
# Otherwise, the python-script is started inside the sbatch-script,
# which's end is awaited (by checking squeue every 10 seconds in the
# background if the started job is still there, and, if --follow is
# defined, a tail -f on the slurm.out file is loaded in the foreground).
# This way, the whole slurm procedure is transparent to the user,
# and the program looks basically the same on every device.

export NO_WHIPTAIL=1

function displaytime {
	local T=$1
		local D=$((T/60/60/24))
		local H=$((T/60/60%24))
		local M=$((T/60%60))
		local S=$((T%60))
		(( $D > 0 )) && printf '%d days ' $D
		(( $H > 0 )) && printf '%d hours ' $H
		(( $M > 0 )) && printf '%d minutes ' $M
		(( $D > 0 || $H > 0 || $M > 0 )) && printf 'and '
		printf '%d seconds\n' $S
}

#SBATCH --signal=B:USR1@200

export CUDA_DEVICE_ORDER=PCI_BUS_ID
export ORIGINAL_PWD=$(pwd)

set -e
set -o pipefail

function mycd () {
	#echo "cd $1"
	cd $1
}


slurmlogpath () {
	if command -v scontrol 2>/dev/null >/dev/null; then
		scontrol show job $1 | grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn} StdOut | sed -e 's/^\s*StdOut=//'
	fi
}

function echoerr() {
        echo "$@" 1>&2
}

function yellow_text {
	echoerr -e "\e\033[0;33m$1\e[0m"
}

function green_text {
	echoerr -e "\033[0;32m$1\e[0m"
}

function red_text {
	echoerr -e "\e[31m$1\e[0m"
}

function calltracer () {
	yellow_text "Git status hash:"
	git rev-parse HEAD
        red_text 'Error occured in file/line:'
        caller

	echo "Runtime: $(displaytime $SECONDS)"
	tput bel
}

already_sent_signal=

kill_python_if_started () {
	REASON=$1
	echo "kill_python_if_started $REASON"
	re='^[0-9]+$'
	if ! [[ -z "$SLURM_JOB_ID" ]]; then
		if [[ $python_pid =~ $re ]] ; then
			if [[ -z "$already_sent_signal" ]]; then
				if ps auxf | grep $python_pid 2>/dev/null >/dev/null; then
					already_sent_signal=1
					echo -e "\nSending USR1 to $python_pid (python). Reason: $REASON"
					kill -USR1 "$python_pid"
				else
					echo "Could not find $python_pid process" >&2
				fi
			fi
		fi
	fi

	echo "Runtime: $(displaytime $SECONDS)"
	tput bel
}

trap 'calltracer' ERR
trap 'kill_python_if_started CONT' CONT
trap 'kill_python_if_started TERM' TERM

for i in $(kill -l 2>&1 | sed -e 's#[0-9][0-9]*\s*)##g'); do
	if
		[[ "$i" != "ERR" ]] &&
		[[ "$i" != "CONT" ]] &&
		[[ "$i" != "TERM" ]] &&
		[[ "$i" != "CHLD" ]] &&
		[[ "$i" != "SIGCHLD" ]] &&
		[[ "$i" != "SIGWINCH" ]] &&
		[[ "$i" != "WINCH" ]] &&
		[[ "$i" != "INT" ]] &&
		[[ "$i" != "SIGINT" ]];
	then
		trap "kill_python_if_started $i" $i
	fi
done

minutes_to_hh_mm_ss() {
	var=$1

	number_re='^[0-9]+$'
	time_re='^[0-9]+:[0-9]+:[0-9]+$'

	if [[ $var =~ $number_re ]] ; then
		local total_minutes="$var"
		local hours=$(( total_minutes / 60 ))
		local minutes=$(( total_minutes % 60 ))
		local seconds=00

		printf "%02d:%02d:%02d\n" "$hours" "$minutes" "$seconds"
	elif [[ $var =~ $time_re ]]; then
		echo $var
	else
		red_text "ERROR: $var is not a valid input. Must be a number of minutes (digits) or HH:MM:SS"

		exit 103
	fi
}

int_re='^[+-]?[0-9]+$'

continue_previous_job=""
mem_gb=
gpus=
time=
experiment_name=
help=0
follow=0
debug=0
wait_until_ended=0
tests=0

args_string=""

args=("$@")
k=0
while [ $k -lt ${#args[@]} ]; do
	i="${args[k]}"

	case $i in
		--continue=*)
			old_continue=$continue_previous_job
			continue_previous_job="${i#*=}"

			if [[ ! -z $old_continue ]]; then
				red_text "--continue was specified more than once. Using the last one."
				args_string=$(echo "$args_string" | sed -e 's#\s*--continue=.*\s\s*# #')
			fi

			args_string+=" --continue $continue_previous_job "

			continue_previous_job=$continue_previous_job

			;;
		--continue)
			old_continue=$continue_previous_job

			shift
			k=$((k+1))

			continue_previous_job="${args[k]}"

			if [[ ! -z $old_continue ]]; then
				red_text "--continue was specified more than once. Using the last one."
				args_string=$(echo "$args_string" | sed -e 's#\s*--continue=.*\s\s*# #')
			fi

			args_string+=" --continue $continue_previous_job "

			continue_previous_job=$continue_previous_job

			;;

		--continue_previous_job=*)
			old_continue=$continue_previous_job
			continue_previous_job="${i#*=}"

			if [[ ! -z $old_continue ]]; then
				red_text "--continue was specified more than once. Using the last one."
				args_string=$(echo "$args_string" | sed -e 's#\s*--continue=.*\s\s*# #')
			fi

			args_string+=" --continue $continue_previous_job "

			continue_previous_job=$continue_previous_job

			;;

		--continue_previous_job)
			old_continue=$continue_previous_job

			shift
			k=$((k+1))

			continue_previous_job="${args[k]}"

			if [[ ! -z $old_continue ]]; then
				red_text "--continue was specified more than once. Using the last one."
				args_string=$(echo "$args_string" | sed -e 's#\s*--continue.*\s\s*# #')
			fi

			args_string+=" --continue $continue_previous_job "

			continue_previous_job=$continue_previous_job

			;;

		--mem_gb=*)
			old_mem_gb=$mem_gb
			mem_gb="${i#*=}"
			if ! [[ $mem_gb =~ $int_re ]] ; then
				red_text "error: --mem_gb not a INT: $i" >&2
				exit 100
			fi

			if [[ ! -z $old_mem_gb ]]; then
				red_text "--mem_gb was specified more than once. Using the last one."
				args_string=$(echo "$args_string" | sed -e 's#\s*--mem_gb=[0-9]*\s\s*# #')
			fi

			args_string+=" --mem_gb=$mem_gb "

			;;
		--mem_gb)
			old_mem_gb=$mem_gb

			shift
			k=$((k+1))

			mem_gb="${args[k]}"
			if ! [[ $mem_gb =~ $int_re ]] ; then
				red_text "error: --mem_gb not a INT: $i" >&2
				exit 100
			fi

			if [[ ! -z $old_mem_gb ]]; then
				red_text "--mem_gb was specified more than once. Using the last one."
				args_string=$(echo "$args_string" | sed -e 's#\s*--mem_gb=[0-9]*\s\s*# #')
			fi

			args_string+=" --mem_gb=$mem_gb "

			;;

		--gpus=*)
			old_gpus=$gpus
			gpus="${i#*=}"
			if ! [[ $gpus =~ $int_re ]] ; then
				red_text "error: --gpus not a INT: $i" >&2
				exit 100
			fi

			if [[ ! -z $old_gpus ]]; then
				red_text "--gpus was specified more than once. Using the last one."
				args_string=$(echo "$args_string" | sed -e 's#\s*--gpus=[0-9]*\s\s*# #')
			fi

			args_string+=" --gpus=$gpus "

			;;
		--gpus)
			old_gpus=$gpus

			shift

			k=$((k+1))
			gpus="${args[k]}"
			if ! [[ $gpus =~ $int_re ]] ; then
				red_text "error: --gpus not a INT: $i" >&2
				exit 100
			fi

			if [[ ! -z $old_gpus ]]; then
				red_text "--gpus was specified more than once. Using the last one."
				args_string=$(echo "$args_string" | sed -e 's#\s*--gpus=[0-9]*\s\s*# #')
			fi

			args_string+=" --gpus=$gpus "

			;;

		--experiment_name=*)
			old_experiment_name=$experiment_name
			experiment_name="${i#*=}"

			if [[ ! -z $old_experiment_name ]]; then
				red_text "--experiment_name was specified more than once. Using the last one."
				args_string=$(echo "$args_string" | sed -e 's#\s*--experiment_name=[0-9a-zA-Z_]*\s\s*# #')
			fi

			args_string+=" --experiment_name=$experiment_name "

			;;
		--experiment_name)
			old_experiment_name=$experiment_name

			shift

			k=$((k+1))
			experiment_name="${args[k]}"

			if [[ ! -z $old_experiment_name ]]; then
				red_text "--experiment_name was specified more than once. Using the last one."
				args_string=$(echo "$args_string" | sed -e 's#\s*--experiment_name=[0-9a-zA-Z_]*\s\s*# #')
			fi

			args_string+=" --experiment_name=$experiment_name "

			;;

		--time=*)
			old_time=$time
			time="${i#*=}"

			if [[ ! -z $old_time ]]; then
				red_text "--time was specified more than once. Using the last one."
				args_string=$(echo "$args_string" | sed -e 's#\s*--time=[0-9a-zA-Z_]*\s\s*# #')
			fi

			args_string+=" --time=$time "

			;;
		--time)
			old_time=$time

			shift

			k=$((k+1))
			time="${args[k]}"

			if [[ ! -z $old_time ]]; then
				red_text "--time was specified more than once. Using the last one."
				args_string=$(echo "$args_string" | sed -e 's#\s*--time=[0-9a-zA-Z_]*\s\s*# #')
			fi

			args_string+=" --time=$time "

			;;

		--tests)
			tests=1
			;;

		--follow)
			follow=1
			;;
		--wait_until_ended)
			wait_until_ended=1
			args_string+=" --wait_until_ended "
			;;
		-h)
			help=1
			args_string+=" --help "
			;;
		--help)
			help=1
			args_string+=" --help "
			;;
		--debug)
			debug=1
			;;

		*)
			args_string+=" $i "
			;;
	esac
	k=$((k+1))
done

if [[ "$debug" -eq "1" ]]; then
	set -x
fi


if [[ -z "$SLURM_JOB_ID" ]]; then
	echo "Current git-hash: $(git rev-parse HEAD)"
fi

set +x
if [[ -d ".git" ]]; then
	if command -v whiptail 2>/dev/null >/dev/null; then
		if [[ ! -e .dont_ask_upgrade_omniopt ]]; then
			CURRENTHASH=$(git rev-parse HEAD)

			REMOTEURL=$(git config --get remote.origin.url)
			REMOTEHASH=$(git ls-remote $REMOTEURL HEAD | awk '{ print $1}')

			if [ ! "$CURRENTHASH" = "$REMOTEHASH" ]; then
				eval `resize`
				if (whiptail --title "There is a new version of OmniOpt available" --yesno "Do you want to upgrade?" $LINES $COLUMNS $(( $LINES - 8 ))); then
					git pull
					eval "./$SCRIPT_DIR/omniopt $args_string"
					exit
				else
					eval `resize`
					if (whiptail --title "Ask again?" --yesno "You chose not to upgrade. Ask again at next start?" $LINES $COLUMNS $(( $LINES - 8 ))); then
						echo "Asking again next time if you want to upgrade"
					else
						green_text "OK, not asking again"
						touch .dont_ask_upgrade_omniopt
					fi
				fi
			fi
		fi
	fi
fi

if [[ "$debug" -eq "1" ]]; then
	set -x
fi

args_string=$(echo "$args_string" | sed -e 's#\s\s*# #g')

if [[ -z $gpus ]]; then
	gpus=0
fi

if [[ $tests -eq 0 ]]; then
	if [[ $help -eq 0 ]] && command -v sbatch >/dev/null; then
		if [[ "$continue_previous_job" == "" ]]; then
			if [[ -z "$mem_gb" ]]; then
				red_text "Parameter --mem_gb is missing or empty";
				exit 101
			fi

			if [[ -z "$time" ]]; then
				red_text "Parameter --time is missing or empty";
				exit 102
			fi

			if [[ -z $experiment_name ]]; then
				red_text "Parameter --experiment_name is missing or empty"
				exit 104
			fi
		fi
	fi
fi

if [[ "$continue_previous_job" != "" ]]; then
	if [[ -z "$mem_gb" ]]; then
		if [[ -e "$continue_previous_job/mem_gb" ]]; then
			mem_gb=$(cat "$continue_previous_job/mem_gb")
		else
			echo "mem_gb could not be determined from previous run or --mem_gb"
			exit 105
		fi
	fi

	if [[ -z "$gpus" ]]; then
		if [[ -e "$continue_previous_job/gpus" ]]; then
			gpus=$(cat "$continue_previous_job/gpus")
		else
			echo "gpus could not be determined from previous run or --gpus"
			exit 105
		fi
	fi

	if [[ -z "$time" ]]; then
		if [[ -e "$continue_previous_job/time" ]]; then
			time=$(cat "$continue_previous_job/time")
		else
			echo "Time could not be determined from previous run or --time"
			exit 105
		fi
	fi
fi

python_pid=""

JOB_START_TIME=$SLURM_JOB_START_TIME
JOB_END_TIME=$SLURM_JOB_END_TIME

run_before_end () {
	if [[ -z "$already_sent_signal" ]]; then
		if command -v sbatch >/dev/null; then
			# Weird solution, but signals never reached for some reason, and this... works?
			sleep_time=$((JOB_END_TIME - JOB_START_TIME - 100))
			# Überprüfen, ob die Zeitdifferenz positiv ist, um zu vermeiden, dass das Skript im negativen Bereich schläft
			if [ $sleep_time -gt 0 ]; then
				sleep $sleep_time

				kill_python_if_started "Timeout"
			else
				echo "It is recommended that you run this in a slurm job."
			fi
		fi
	fi
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ -n "${SLURM_JOB_ID:-}" ] ; then
	set +e
	if command -v scontrol 2>/dev/null >/dev/null; then
		SLURM_FILE_SCRIPT_DIR=$(scontrol show job "$SLURM_JOB_ID" | awk -F= '/Command=/{print $2}')
		SLURM_FILE_SCRIPT_DIR=$(dirname $SLURM_FILE_SCRIPT_DIR)
		set -e

		if [[ -d $SLURM_FILE_SCRIPT_DIR ]]; then
			SCRIPT_DIR="$SLURM_FILE_SCRIPT_DIR"
		else
			echo "SLURM_FILE_SCRIPT_DIR $SLURM_FILE_SCRIPT_DIR not found, even though SLURM_JOB_ID exists ($SLURM_JOB_ID). Using SCRIPT_DIR=$SCRIPT_DIR"
		fi
	else
		red_text "scontrol not found. Unsetting SLURM_JOB_ID"
		unset SLURM_JOB_ID
	fi
fi

set +x
source $SCRIPT_DIR/.shellscript_functions

mycd "$ORIGINAL_PWD"
if [[ "$debug" -eq "1" ]]; then
	set -x
fi

if [[ "$help" -eq "1" ]]; then
	python3 $SCRIPT_DIR/.omniopt.py --help
	exit 0
fi

if [[ "$tests" -eq "1" ]]; then
	python3 $SCRIPT_DIR/.omniopt.py --tests --num_parallel_jobs=1 --max_eval=1 --worker_timeout=1 --run_program "" --experiment_name ""
	exit $?
fi

kill_tail_when_squeue_job_empty () {
	JOB_ID=$1

	sleep 10

	while squeue -u $USER | grep "$JOB_ID" 2>/dev/null >/dev/null; do
		sleep 5
	done

	sleep 10

	for child in $(pgrep -P $$); do
		for tail_process in $(ps auxf | grep $child | grep tail | sed -e "s#^$USER\s*##" -e 's#\s.*##'); do
			kill -9 $tail_process
		done
	done

	return 0
}

if [ -n "${SLURM_JOB_ID:-}" ] || ! command -v sbatch >/dev/null; then
	# To start all subjobs indenpedently from the omniopt job, unset all SLURM variables
	set +x
	for i in $(env | egrep "^SLURM" | sed -e 's#\s*=.*##' | grep -v SLURM_JOB_ID | grep -v SBATCH_RESERVATION); do
		unset $i
	done

	if [[ "$debug" -eq "1" ]]; then
		set -x
	fi

	if [[ ! -z $SLURM_JOB_ID ]]; then
		echo -e "To cancel, use '\e[31mscancel $SLURM_JOB_ID\e[0m'"
	fi

	IFS=$' '
	export PYTHONPATH=$SCRIPT_DIR:$PYTHONPATH
	#echo "python3 $SCRIPT_DIR/.omniopt.py $args_string"

	#run_before_end &

	set +e
	python3 $SCRIPT_DIR/.omniopt.py $args_string &
	python_pid=$!
	wait $python_pid
	EXIT_CODE=$?

	set -e

	if [[ "$EXIT_CODE" -ne "0" ]]; then
		echo "Exiting with exit-code $EXIT_CODE"
	fi

	tput bel

	exit $EXIT_CODE
else
	IFS=$' '

	formatted_time=$(minutes_to_hh_mm_ss $time)

	sbatch_result=""
	exit_code=""

	if [[ $gpus -ne 0 ]]; then
		sbatch_result=$(sbatch --job-name "$experiment_name" --time=$formatted_time --mem=${mem_gb}GB --gres=gpu:$gpus $SCRIPT_DIR/omniopt $args_string | tee /dev/stderr)
		exit_code=$?
	else
		sbatch_result=$(sbatch --job-name "$experiment_name" --time=$formatted_time --mem=${mem_gb}GB $SCRIPT_DIR/omniopt $args_string | tee /dev/stderr)
		exit_code=$?
	fi

	started_job_nr=$(echo "$sbatch_result" | sed -e 's#.*\s##')

	if [[ $exit_code -eq 0 ]]; then
		if [[ $follow -eq 1 ]]; then
			if command -v sbatch 2>/dev/null >/dev/null; then
				LOG_PATH=$(slurmlogpath $started_job_nr)
	
				spin[0]="-"
				spin[1]="\\" # "
				spin[2]="|"
				spin[3]="/"

				set +x

				echo -n "Waiting until the path $LOG_PATH exists. CTRL-c does NOT cancel the optimization, only the tail...  "

				while ! [[ -e $LOG_PATH ]]; do
					for i in "${spin[@]}"; do
						echo -ne "\b$i"
						sleep 0.1
					done
				done

				if [[ "$debug" -eq 1 ]]; then
					set -x
				fi

				printf "\r"

				tput el

				if [[ -e "$LOG_PATH" ]]; then
					set +x
					kill_tail_when_squeue_job_empty $started_job_nr &
					# weird exec stuff for disabling the "Terminated" message coming from kill
					exec 3>&2          # 3 is now a copy of 2
					exec 2> /dev/null  # 2 now points to /dev/null
					tail -n1000000 -f $LOG_PATH || true
					exec 2>&3          # restore stderr to saved
					exec 3>&-          # close saved version
					if [[ "$debug" -eq "1" ]]; then
						set -x
					fi

					exit_code=$(cat $LOG_PATH | grep -i "exit-code" | sed -e 's#Exit-Code:\s*##i')
				else
					red_text "$LOG_PATH could not be found"
				fi
			fi
		elif [[ "$wait_until_ended" -eq "1" ]]; then
			if command -v squeue 2>/dev/null >/dev/null; then
				WAIT_NUM_SECONDS=10
				yellow_text "Waiting for job $started_job_nr to end... (Checking every $WAIT_NUM_SECONDS seconds)"

				set +x

				seconds_count=0

				echo ""

				while [[ "$(squeue --me | grep $started_job_nr | wc -l)" -ne "0" ]]; do
					sleep $WAIT_NUM_SECONDS
				done

				echo ""

				if [[ "$debug" -eq 1 ]]; then
					set -x
				fi

				yellow_text "Done waiting for job to end"

				LOG_PATH=$(slurmlogpath $started_job_nr)
				if [[ -e "$LOG_PATH" ]]; then
					cat $LOG_PATH
				else
					red_text "$LOG_PATH could not be found"
				fi
			else
				red_text "squeue not found. Cannot wait for job to end."
			fi
		fi
	else
		red_text "Failed to start sbatch job. Exit-Code: $exit_code"

		exit $exit_code
	fi

fi

echo "Runtime: $(displaytime $SECONDS)"
exit $exit_code
