#!/bin/bash

function echoerr() {
        echo "$@" 1>&2
}

function yellow_text {
        echoerr -e "\e\033[0;33m$1\e[0m"
}

function red_text {
        echoerr -e "\e[31m$1\e[0m"
}

function green_text {
        echoerr -e "\e\033[0;32m$1\e[0m"
}

export NO_WHIPTAIL=1
export NO_RUNTIME=1

if [[ ! -d "runs/" ]]; then
	echo "runs is not a directory. Cannot continue"
	exit 1
fi

for plot_type in $(ls .omniopt_plot_*.py | grep -v 3d | sed -e 's#\.omniopt_plot_##' | sed -e 's#\.py##'); do
	for project in $(ls runs); do
		for project_nr in $(ls runs/$project); do
			yellow_text "./omniopt_plot --run_dir runs/$project/$project_nr --plot_type=$plot_type --no_plt_show"
			./omniopt_plot --run_dir runs/$project/$project_nr --plot_type=$plot_type --no_plt_show
		done
	done
done
