#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

function join_by {
	local d=${1-} f=${2-}
	if shift 2; then
		printf %s "$f" "${@/#/$d}"
	fi
}

function echoerr() {
        echo "$@" 1>&2
}

function yellow_text {
        echoerr -e "\e\033[0;33m$1\e[0m"
}

function red_text {
        echoerr -e "\e[31m$1\e[0m"
}

function green_text {
        echoerr -e "\e\033[0;32m$1\e[0m"
}

set -o pipefail

function calltracer () {
	yellow_text "Git status hash:"
	git rev-parse HEAD
        red_text 'Error occured in file/line:'
        caller
}

trap 'calltracer' ERR

function help () {
        echo "Possible options:"
	echo "  --max_eval=(INT)                                   Number of max evals for this test"
	echo "  --no_sleep                                         Disables sleeping after job creation (not recommended on HPC)"
        echo "  --help                                             this help"
        echo "  --debug                                            Enables debug mode (set -x)"
        exit $1
}

NUM_GPUS=0
if command -v nvidia-smi 2>/dev/null >/dev/null; then
	NUM_GPUS=$(nvidia-smi --list-gpus | wc -l)
fi

if [[ "$NUM_GPUS" -ne "0" ]]; then
	NUM_GPUS=1
fi

debug=0
max_eval=20
no_sleep=0

args=("$@")
k=0
while [ $k -lt ${#args[@]} ]; do
	i="${args[k]}"

	case $i in
		--max_eval=*)
			old_max_eval=$max_eval
			max_eval="${i#*=}"
			if ! [[ $max_eval =~ $int_re ]] ; then
				red_text "error: --max_eval not a INT: $i" >&2
				exit 100
			fi

			;;
		--max_eval)
			old_max_eval=$max_eval

			shift
			k=$((k+1))

			max_eval="${args[k]}"
			if ! [[ $max_eval =~ $int_re ]] ; then
				red_text "error: --max_eval not a INT: $i" >&2
				exit 100
			fi

			;;
		--no_sleep)
			no_sleep=1
			;;
		--help*)
			help 1
			;;
		--debug)
			debug=1
			;;

		*)
			red_text "Unknown parameter $i"
			exit 2
			;;
	esac
	k=$((k+1))
done

if [[ "$max_eval" -lt "1" ]]; then
	red_text "Max_eval must be 1 or more, is $max_eval"
	exit 1
fi

if [[ "$debug" -eq "1" ]]; then
	set -x
fi


PARTITION="alpha"
GPUS=0
TESTNAME=__main__tests__

if [[ "$PARTITION" == "alpha" ]]; then
	GPUS=1
fi


errors=()

cd ..

./omniopt --tests --mem_gb 1 --time 1 --experiment_name test_name --debug
exit_code=$?
if [[ "$exit_code" -ne "0" ]]; then
	errors+=("Simple tests failed")
fi

# ./.tests/optimization_example --int_param=%(int_param) --float_param=%(float_param) --choice_param=%(choice_param)  --int_param_two=%(int_param_two)

if [[ -d "runs/$TESTNAME" ]]; then
	yellow_text "Deleting old runs/$TESTNAME..."
	if [[ -d runs/$TESTNAME ]]; then
		rm -rf runs/$TESTNAME
	fi
fi

yellow_text "Starting main program..."

if [[ "$no_sleep" -eq 1 ]]; then
	./omniopt \
		--debug \
		--partition=$PARTITION \
		--experiment_name=$TESTNAME \
		--mem_gb=1 \
		--time=30 \
		--worker_timeout=1 \
		--max_eval=$max_eval \
		--num_parallel_jobs=$max_eval \
		--gpus=$GPUS \
		--run_program=$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0) \
		--parameter int_param range -5 5 int \
		--parameter float_param range -5 5 float \
		--parameter choice_param choice 1,2,4,8,16,hallo \
		--parameter int_param_two range -6 6 int \
		--follow \
		--no_sleep
else
	./omniopt \
		--debug \
		--partition=$PARTITION \
		--experiment_name=$TESTNAME \
		--mem_gb=1 \
		--time=30 \
		--worker_timeout=1 \
		--max_eval=$max_eval \
		--num_parallel_jobs=$max_eval \
		--gpus=$GPUS \
		--run_program=$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0) \
		--parameter int_param range -5 5 int \
		--parameter float_param range -5 5 float \
		--parameter choice_param choice 1,2,4,8,16,hallo \
		--parameter int_param_two range -6 6 int \
		--follow
fi

exit_code=$?

yellow_text "Main program ended..."

if [[ "$exit_code" -ne "0" ]]; then
	errors+=("omniopt script failed.")
fi

yellow_text "Trying to continue previous job"

./omniopt --debug --continue runs/__main__tests__/0 --num_parallel_jobs 10 --worker_timeout 10 --follow --gpus=$NUM_GPUS

exit_code=$?

yellow_text "Continuation program ended..."

if [[ "$exit_code" -ne "0" ]]; then
	errors+=("Continuation script failed.")
fi

yellow_text "Trying to continue non-existing job"

if [[ -d "runs/__main__I_DO_NOT_EXIST_tests__/0" ]]; then
	yellow_text "Deleting runs/__main__I_DO_NOT_EXIST_tests__/0"
	rm -rf runs/__main__I_DO_NOT_EXIST_tests__/0
fi

./omniopt --debug --continue runs/__main__I_DO_NOT_EXIST_tests__/0 --num_parallel_jobs 10 --worker_timeout 10 --max_eval 10 --mem_gb 1 --time 10 --follow --gpus=$NUM_GPUS || true
PE=$PIPEERROR

exit_code=$?

yellow_text "Continuation failed program ended..."

if [[ "$exit_code" -ne "0" ]]; then
	errors+=("Continuation of failed path failed with $(echo $PE | sed -e 's#\|.*##')")
fi

yellow_text "Calling plot function for runs/$TESTNAME/0"

TMP_FILE_PATH="._test_run.svg"
./omniopt_plot --run_dir runs/$TESTNAME/0 --save_to_file $TMP_FILE_PATH

yellow_text "Checking plot function"
if [[ -e $TMP_FILE_PATH ]]; then
	if cat $TMP_FILE_PATH | grep Minimum 2>/dev/null >/dev/null; then
		if cat $TMP_FILE_PATH | grep float_param 2>/dev/null >/dev/null; then
			number_of_evals_run=$(cat $TMP_FILE_PATH | grep "Number of evaluations shown"  | sed -e 's#\s*-->##' | sed -e 's#.*\s##' | sed -e 's#\s##g')
			if [[ "$number_of_evals_run" -eq "$max_eval" ]] || [[ "$number_of_evals_run" -gt "$max_eval" ]]; then
				green_text "Minimum, float_param found, also number_of_evals_run matches max_eval or is larger than it (max_eval = $max_eval, number_of_evals_run = $number_of_evals_run)"
			else
				errors+=("number_of_evals_run ($number_of_evals_run) does not match wanted max_eval ($max_eval)")
			fi
		else
			errors+=("word 'float_param' not found in $TMP_FILE_PATH")
		fi
	else
		errors+=("word 'minimum' not found in $TMP_FILE_PATH")
	fi

	yellow_text "$TMP_FILE_PATH found and checked. Deleting it."
	rm $TMP_FILE_PATH
else
	errors+=("$TMP_FILE_PATH not found")
fi

yellow_text "Deleting runs/test_wronggoing_stuff/..."
if [[ -d runs/test_wronggoing_stuff/ ]]; then
	rm -rf runs/test_wronggoing_stuff/
fi

yellow_text "Test stuff that goes wrong..."

.tests/test_wronggoing_stuff

exit_code=$?
if [[ "$exit_code" -ne "0" ]]; then
	errors+=("test_wronggoing_stuff failed")
fi

yellow_text "Test stuff that goes wrong (totally without successful runs)..."

.tests/test_wronggoing_stuff

exit_code=$?
if [[ "$exit_code" -ne "0" ]]; then
	errors+=("test_wronggoing_stuff (without successes) failed")
fi

if [ ${#errors[@]} -eq 0 ]; then
	green_text "No errors"
	exit 0
else
	for i in "${errors[@]}"; do
		red_text "$i"
	done

	exit ${#errors[@]}
fi

