#!/bin/bash

export NO_WHIPTAIL=1

errors=()

function join_by {
	local d=${1-} f=${2-}
	if shift 2; then
		printf %s "$f" "${@/#/$d}"
	fi
}

function echoerr() {
        echo "$@" 1>&2
}

function yellow_text {
        echoerr -e "\e\033[0;33m$1\e[0m"
}

function red_text {
        echoerr -e "\e[31m$1\e[0m"
}

function green_text {
        echoerr -e "\e\033[0;32m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

expected_plot_types=()

for possible_plot_type in $(ls .omniopt_plot_*.py | sed -e 's#\.py##' -e 's#.*_plot_##' | grep -v 3d); do
	expected_plot_types+=("$possible_plot_type")
done

for possible_plot_type in "${expected_plot_types[@]}"; do
	if ! grep "plot_type=$possible_plot_type" .gui/tutorials/plot.php 2>&1 >/dev/null; then
		errmsg="Plot type $possible_plot_type does not appear in .gui/tutorials/plot.php"
		red_text "$errmsg"
		errors+=("$errmsg")
	fi

	fn="$possible_plot_type.txt"

	mkdir -p .gui/tutorials/plot_helps/
	#bash omniopt_plot --plot_type $possible_plot_type --help | grep -- "--" | sed -e 's#^\s*##' -e 's#usage.*\.py.##' -e 's#\]##' | grep -v "expected one argument" | sed -e 's#\s#\n#g' | grep "^\[" | sed -e 's#^\[##g' | sed -e 's#\]##g' | grep -- "^--" > .gui/tutorials/plot_helps/$fn


	if ! grep "plot_helps/$fn" .gui/tutorials/plot.php 2>&1 >/dev/null; then
		errmsg="file plot_helps/$fn for $possible_plot_type does not appear in .gui/tutorials/plot.php"
		red_text "$errmsg"
		errors+=("$errmsg")
	fi
done

secs=$SECONDS
hrs=$(( secs/3600 )); mins=$(( (secs-hrs*3600)/60 )); secs=$(( secs-hrs*3600-mins*60 ))
printf 'plot_documentation_has_all_plot_types took: %02d:%02d:%02d\n' $hrs $mins $secs

if [ ${#errors[@]} -eq 0 ]; then
	green_text "No plot_documentation_has_all_plot_types errors"
	exit 0
else
	red_text "=> PLOT_DOCUMENTATION-ERRORS => PLOT_DOCUMENTATION-ERRORS => PLOT_DOCUMENTATION-ERRORS =>"
	for i in "${errors[@]}"; do
		red_text "$i"
	done

	exit ${#errors[@]}
fi
