#!/bin/bash

export NO_WHIPTAIL=1

run_dir=$1

function join_by {
	local d=${1-} f=${2-}
	if shift 2; then
		printf %s "$f" "${@/#/$d}"
	fi
}

for i in $(ls $run_dir | sort -n); do
	if [[ ! -e "$i.png" ]]; then
		echo "Creating $i.png"
		bash omniopt_plot --run_dir $run_dir/$i --save_to_file "$i.png" --bubblesize 50 --exclude choice_param
	fi
done

for i in $(ls *.png | sort -n | sed -e 's#\.png##'); do
	if [[ ! -e "${i}_with_text.jpg" ]]; then
		echo "Creating ${i}_with_text.png"
		convert ${i}.png -gravity North -pointsize 30 -annotate +-660+0 "${i}" ${i}_with_text.png
	fi
done

echo "Converting to gif"
convert -size 1080x1080 -delay 120 -loop 0 $(ls *_with_text.png | sort -n) output.gif

rm *.png

echo "file: output.gif"
